
services:
  site1:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - ./sites/site1:/usr/share/nginx/html:ro

  site2:
    image: nginx
    ports:
      - "8082:80"
    volumes:
      - ./sites/site2:/usr/share/nginx/html:ro
